In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
%matplotlib inline

In [4]:
df = pd.read_csv('StorePred.csv', index_col = 0)

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (26,42,43,88) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
df.head()

,ZipCode,PrimaryRecord,Population,HouseholdsPerZipcode,WhitePopulation,BlackPopulation,HispanicPopulation,AsianPopulation,HawaiianPopulation,IndianPopulation,...,ZIPIntroDate,AliasIntroDate,FacilityCode,CityDeliveryIndicator,CarrierRouteRateSortation,FinanceNumber,UniqueZIPName,InternationalStoreCode,NickName,PhyscialStore
0,96201,P,0,0,0,0,0,0,0,0,...,<2004-10,<2004-10,P,N,C,610001,NoStore,0,NoStore,0.0
1,96202,P,0,0,0,0,0,0,0,0,...,<2004-10,<2004-10,P,N,C,610001,NoStore,0,NoStore,0.0
2,96203,P,0,0,0,0,0,0,0,0,...,<2004-10,<2004-10,P,N,C,610001,NoStore,0,NoStore,0.0
3,96204,P,0,0,0,0,0,0,0,0,...,<2004-10,<2004-10,P,N,C,610001,NoStore,0,NoStore,0.0
4,96205,P,0,0,0,0,0,0,0,0,...,<2004-10,<2004-10,P,N,C,610001,NoStore,0,NoStore,0.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41720 entries, 0 to 41719
Data columns (total 90 columns):
ZipCode                        41720 non-null int64
PrimaryRecord                  41720 non-null object
Population                     41720 non-null int64
HouseholdsPerZipcode           41720 non-null int64
WhitePopulation                41720 non-null int64
BlackPopulation                41720 non-null int64
HispanicPopulation             41720 non-null int64
AsianPopulation                41720 non-null int64
HawaiianPopulation             41720 non-null int64
IndianPopulation               41720 non-null int64
OtherPopulation                41720 non-null int64
MalePopulation                 41720 non-null int64
FemalePopulation               41720 non-null int64
PersonsPerHousehold            41720 non-null float64
AverageHouseValue              41720 non-null int64
IncomePerHousehold             41720 non-null int64
MedianAge                      41720 non-null float64
MedianAgeMale                  41720 non-null float64
MedianAgeFemale                41720 non-null float64
Latitude                       41720 non-null float64
Longitude                      41720 non-null float64
Elevation                      41720 non-null int64
State                          41720 non-null object
StateFullName                  41124 non-null object
CityType                       41720 non-null object
CityAliasAbbreviation          2192 non-null object
AreaCode                       41716 non-null object
City                           41720 non-null object
CityAliasName                  41720 non-null object
County                         41124 non-null object
CountyFIPS                     41124 non-null float64
StateFIPS                      41124 non-null float64
TimeZone                       41720 non-null int64
DayLightSaving                 41720 non-null object
MSA                            21995 non-null float64
PMSA                           8249 non-null float64
CSA                            23300 non-null float64
CBSA                           31874 non-null float64
CBSA_DIV                       5503 non-null float64
CBSA_Type                      31874 non-null object
CBSA_Name                      31874 non-null object
MSA_Name                       21995 non-null object
PMSA_Name                      8249 non-null object
Region                         40905 non-null object
Division                       40905 non-null object
MailingName                    41720 non-null object
NumberOfBusinesses             41720 non-null int64
NumberOfEmployees              41720 non-null int64
BusinessFirstQuarterPayroll    41720 non-null int64
BusinessAnnualPayroll          41720 non-null int64
BusinessEmploymentFlag         4928 non-null object
GrowthRank                     41720 non-null int64
GrowthHousingUnits2009         0 non-null float64
GrowthHousingUnits2010         0 non-null float64
GrowthIncreaseNumber           41720 non-null int64
GrowthIncreasePercentage       41720 non-null float64
CBSAPop2003                    0 non-null float64
CBSADivPop2003                 0 non-null float64
CongressionalDistrict          38705 non-null object
CongressionalLandArea          38705 non-null object
DeliveryResidential            41720 non-null int64
DeliveryBusiness               41720 non-null int64
DeliveryTotal                  41720 non-null int64
PreferredLastLineKey           41720 non-null object
ClassificationCode             11898 non-null object
MultiCounty                    8464 non-null object
CSAName                        23300 non-null object
CBSA_DIV_Name                  5503 non-null object
CityStateKey                   41720 non-null object
PopulationEstimate             41720 non-null int64
LandArea                       41720 non-null float64
WaterArea                      41720 non-null float64
CityAliasCode                  2774 non-null object
CityMixedCase                  41720 non-null object
CityAliasMixedCase             41720 non-null object
BoxCount                       41720 non-null int64
SFDU                           41720 non-null int64
MFDU                           41720 non-null int64
StateANSI                      41124 non-null float64
CountyANSI                     41093 non-null float64
ZIPIntroDate                   41720 non-null object
AliasIntroDate                 41720 non-null object
FacilityCode                   41720 non-null object
CityDeliveryIndicator          41720 non-null object
CarrierRouteRateSortation      41720 non-null object
FinanceNumber                  41720 non-null int64
UniqueZIPName                  41720 non-null object
InternationalStoreCode         41720 non-null object
NickName                       41720 non-null object
PhyscialStore                  41720 non-null float64
dtypes: float64(23), int64(30), object(37)
memory usage: 29.0+ MB

In [10]:
# to change use .astype() 
# change to interger
df['PhyscialStore'] = df.PhyscialStore.astype('int64')

In [11]:
df.info() # check to see it worked

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41720 entries, 0 to 41719
Data columns (total 90 columns):
ZipCode                        41720 non-null int64
PrimaryRecord                  41720 non-null object
Population                     41720 non-null int64
HouseholdsPerZipcode           41720 non-null int64
WhitePopulation                41720 non-null int64
BlackPopulation                41720 non-null int64
HispanicPopulation             41720 non-null int64
AsianPopulation                41720 non-null int64
HawaiianPopulation             41720 non-null int64
IndianPopulation               41720 non-null int64
OtherPopulation                41720 non-null int64
MalePopulation                 41720 non-null int64
FemalePopulation               41720 non-null int64
PersonsPerHousehold            41720 non-null float64
AverageHouseValue              41720 non-null int64
IncomePerHousehold             41720 non-null int64
MedianAge                      41720 non-null float64
MedianAgeMale                  41720 non-null float64
MedianAgeFemale                41720 non-null float64
Latitude                       41720 non-null float64
Longitude                      41720 non-null float64
Elevation                      41720 non-null int64
State                          41720 non-null object
StateFullName                  41124 non-null object
CityType                       41720 non-null object
CityAliasAbbreviation          2192 non-null object
AreaCode                       41716 non-null object
City                           41720 non-null object
CityAliasName                  41720 non-null object
County                         41124 non-null object
CountyFIPS                     41124 non-null float64
StateFIPS                      41124 non-null float64
TimeZone                       41720 non-null int64
DayLightSaving                 41720 non-null object
MSA                            21995 non-null float64
PMSA                           8249 non-null float64
CSA                            23300 non-null float64
CBSA                           31874 non-null float64
CBSA_DIV                       5503 non-null float64
CBSA_Type                      31874 non-null object
CBSA_Name                      31874 non-null object
MSA_Name                       21995 non-null object
PMSA_Name                      8249 non-null object
Region                         40905 non-null object
Division                       40905 non-null object
MailingName                    41720 non-null object
NumberOfBusinesses             41720 non-null int64
NumberOfEmployees              41720 non-null int64
BusinessFirstQuarterPayroll    41720 non-null int64
BusinessAnnualPayroll          41720 non-null int64
BusinessEmploymentFlag         4928 non-null object
GrowthRank                     41720 non-null int64
GrowthHousingUnits2009         0 non-null float64
GrowthHousingUnits2010         0 non-null float64
GrowthIncreaseNumber           41720 non-null int64
GrowthIncreasePercentage       41720 non-null float64
CBSAPop2003                    0 non-null float64
CBSADivPop2003                 0 non-null float64
CongressionalDistrict          38705 non-null object
CongressionalLandArea          38705 non-null object
DeliveryResidential            41720 non-null int64
DeliveryBusiness               41720 non-null int64
DeliveryTotal                  41720 non-null int64
PreferredLastLineKey           41720 non-null object
ClassificationCode             11898 non-null object
MultiCounty                    8464 non-null object
CSAName                        23300 non-null object
CBSA_DIV_Name                  5503 non-null object
CityStateKey                   41720 non-null object
PopulationEstimate             41720 non-null int64
LandArea                       41720 non-null float64
WaterArea                      41720 non-null float64
CityAliasCode                  2774 non-null object
CityMixedCase                  41720 non-null object
CityAliasMixedCase             41720 non-null object
BoxCount                       41720 non-null int64
SFDU                           41720 non-null int64
MFDU                           41720 non-null int64
StateANSI                      41124 non-null float64
CountyANSI                     41093 non-null float64
ZIPIntroDate                   41720 non-null object
AliasIntroDate                 41720 non-null object
FacilityCode                   41720 non-null object
CityDeliveryIndicator          41720 non-null object
CarrierRouteRateSortation      41720 non-null object
FinanceNumber                  41720 non-null int64
UniqueZIPName                  41720 non-null object
InternationalStoreCode         41720 non-null object
NickName                       41720 non-null object
PhyscialStore                  41720 non-null int64
dtypes: float64(22), int64(31), object(37)
memory usage: 29.0+ MB

,ZipCode,PrimaryRecord,Population,HouseholdsPerZipcode,WhitePopulation,BlackPopulation,HispanicPopulation,AsianPopulation,HawaiianPopulation,IndianPopulation,...,ZIPIntroDate,AliasIntroDate,FacilityCode,CityDeliveryIndicator,CarrierRouteRateSortation,FinanceNumber,UniqueZIPName,InternationalStoreCode,NickName,PhyscialStore
0,96201,P,0,0,0,0,0,0,0,0,...,<2004-10,<2004-10,P,N,C,610001,NoStore,0,NoStore,0
1,96202,P,0,0,0,0,0,0,0,0,...,<2004-10,<2004-10,P,N,C,610001,NoStore,0,NoStore,0
2,96203,P,0,0,0,0,0,0,0,0,...,<2004-10,<2004-10,P,N,C,610001,NoStore,0,NoStore,0
3,96204,P,0,0,0,0,0,0,0,0,...,<2004-10,<2004-10,P,N,C,610001,NoStore,0,NoStore,0
4,96205,P,0,0,0,0,0,0,0,0,...,<2004-10,<2004-10,P,N,C,610001,NoStore,0,NoStore,0